### PR TITLE
MANIFEST.in: Add test.py

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by moskytw** [comment]
Why we should ship with test.py?

**Comment by jayvdb** [comment]
So that distros can run tests from the release tarball at https://pypi.org/project/zipcodetw/#files .  Distros run these tests continuously in order to ensure that the package continues to work when they use a different Python as their default version, and against new versions of Python in order work out which packages will break when they change their default version.

**Comment by moskytw** [comment]
You meant Linux distribution? But zipcodetw now is not included in any distro. I don't see the point.

**Comment by jayvdb** [comment]
I have done the packaging work at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-zipcodetw , so that I can use this package on my Linux distro.

**Comment by moskytw** [comment]
I see. Thanks for pointing that out.

**Pull request merged**
